- name: Create backup directory
  ansible.builtin.file:
    path: backup
    state: directory
  register: local_dir
  delegate_to: localhost
  become: no

- name: Create parachain directory
  ansible.builtin.file:
    path: backup/{{ inventory_hostname }}/parachain/
    state: directory
  register: local_dir
  delegate_to: localhost
  become: no

- name: backup parachain keys
  synchronize:  
    src: '{{ item }}' 
    dest: backup/{{ inventory_hostname }}/parachain/
    mode: pull
    use_ssh_args: yes
  with_items:
    - "{{ db_path }}/chains/anlogcc1/keystore"
    - "{{ db_path }}/chains/anlogcc1/network"